routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/form', function () {
    return view('matrix.html.ltr.web');
    // return view('partials.includes.formulaires.form');
});
// Route::get('/', function () {
//     return view('matrix.html.ltr.web');
//     // return view('partials.includes.formulaires.form');
// });

Route::get('/test1/{etablissement}','Etablissements\DashboardController@test');

Route::get('/testAuth', function () {
    return App\Models\Agents_commune::getUsersByCommune(1);
})->name('test');

// Welcome
Route::get('/',function(){
	return view('welcomeApp');
})->name('login');
Route::post('/',function(){
	$etablissemnt = App\Models\Etablissement::where('slug',request()->slug)->first(	);
	if($etablissemnt){
		return redirect('/'.$etablissemnt->slug);
	}
	Flashy::error('Le Slug entré n\'est pas disponible');
	return redirect()->back();
});

Route::get('logout',function(){
  auth()->logout();
  return redirect('/');
})->name('logout');

/**
* Route pour les agents de la commune
*
**/
// Route::domain('commune.snen.local')->group(function(){
// 		Route::get('/', function () {
// 		    return redirect()->route('commune');
// 		});
Route::get('/agent-commune', 'Auth\AgentCommuneController@showLoginForm')->name('commune');
Route::post('/agent-commune', 'Auth\AgentCommuneController@login')->name('login_agent_commune');
Route::name('commune.')->group(function () {
		Route::get('/welcome','Communes\DashboardController@index')->name('index');
		Route::get('/accueil','Communes\DashboardController@acceuil')->name('accueil');
		Route::get('/archives','Communes\DashboardController@archives')->name('archive');
		Route::get('/view/{declaration}','Communes\DashboardController@viewDeclaration')->name('view_declaration');
		Route::get('/etablissements','Communes\DashboardController@getEtablissements')->name('get_etablissements');
		Route::post('/createEtablissment','Communes\DashboardController@createEtablissements')->name('create_etablissement');
		Route::get('/users','Communes\DashboardController@getUsers')->name('get_users');
		Route::post('/createUser','Communes\DashboardController@createUser')->name('create_user');
		Route::post('/updateUser','Communes\DashboardController@updateUSer')->name('update_user');

		Route::get('/create','Communes\DashboardController@create_declaration')->name('create_declaration');
		Route::post('/create','DeclarationController@store')->name('create_declaration');

		Route::get('/edit/{declaration}','Communes\DashboardController@edit_declaration')->name('edit_declaration');
		Route::post('/edit/{declaration}','DeclarationController@store')->name('edit_declaration');
		Route::get('/archive/{declaration}','Communes\DashboardController@archive_declaration')->name('archive_declaration');


		Route::resource('/crud_etablissements','EtablissementController');

		Route::get('logout-commune',function(){
			auth()->logout();
			request()->session()->flush();

  			return redirect()->route('commune');
		})->name('logout');

	});
// });

// Route pourles utilisateur des établissement 
// Route::domain('hopital.snen.local')->group(function(){
// 		Route::get('/', function () {
// 		    return redirect()->route('user_etablissement');
// 		});

	Route::get('/{etablissement}/login', 'Auth\UserEtablissementController@showLoginForm')->name('user_etablissement');
	Route::post('/{etablissement}/login', 'Auth\UserEtablissementController@login')->name('login_user_etablissement');

	Route::name('etablissement.')->group(function () {
			Route::get('/slug','Etablissements\DashboardController@index1')->name('index1');

			Route::get('/{etablissement}/welcome','Etablissements\DashboardController@index')->name('index');
			Route::get('/{etablissement}/accueil','Etablissements\DashboardController@acceuil')->name('accueil');
			Route::get('/{etablissement}/archives','Etablissements\DashboardController@archives')->name('archive_declaration');
			Route::get('/{etablissement}/create','Etablissements\DashboardController@create_declaration')->name('create_declaration');
			Route::post('/{etablissement}/create','DeclarationController@store')->name('create_declaration');
			Route::get('/{etablissement}/edit/{declaration}','Etablissements\DashboardController@edit_declaration')->name('edit_declaration');
			Route::post('/{etablissement}/edit/{declaration}','DeclarationController@store')->name('edit_declaration');
			Route::get('/{etablissement}/send/{declaration}','Etablissements\DashboardController@send_declaration')->name('send_declaration');
			Route::get('/{etablissement}/destoy/{declaration}','Etablissements\DashboardController@destroy_declaration')->name('delete_declaration');

			Route::get('/{etablissement}/users','Etablissements\DashboardController@getUsers')->name('get_users');
			Route::post('/{etablissement}/createUser','Etablissements\DashboardController@createUser')->name('create_user');
			Route::post('/{etablissement}/updateUser','Etablissements\DashboardController@updateUSer')->name('update_user');
			

			Route::get('/{etablissement}/view/{declaration}','Etablissements\DashboardController@viewDeclaration')->name('view_declaration');

			Route::get('logout-etablissement/{etablissement}',function(App\Models\Etablissement $etablissement){
				\Auth::logout();
				request()->session()->flush();
	  			return redirect()->route('user_etablissement',$etablissement->slug);
			})->name('logout');


		});
	Route::get('/{etablissement}', function(App\Models\Etablissement $etablissement){
		return redirect()->route('user_etablissement',$etablissement->slug);
	});

// });

app/Models/Etablissement.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Etablissement extends Model
{
    

    protected $primaryKey = 'idetablissement';
	public $timestamps = false;
    protected $fillable = [
         'nom', 'abbr','pseudo','idadresse'
    ];

    public function getRouteKeyName(){
    	return 'slug';
    }
    /**
     * Evénement éloquent lors de la creation d'un établissement
     * l'année academique en cours est recuperée automatique
     */
    protected static function boot(){
        parent::boot();

        static::creating(function($etablissement){
           $etablissement->slug = str_slug($etablissement->abbr, $separator = '-');
        });
    }

    public static function getEtablissements(){
    	return self::join('users_etablissements','users_etablissements.idetablissement','etablissements.idetablissement')
    		->where('users_etablissements.isAdmin','=',true)
    		->get([
    				'etablissements.idetablissement',
    				'etablissements.nom',
    				'etablissements.abbr',
                    'etablissements.slug',
    				'etablissements.idadresse',
    				'users_etablissements.pseudo',
    			]);
    }
}

app/Http/Controllers/EtablissementController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\UpdateEtablissementRequest;
use App\Http\Requests\CreateEtablissementRequest;
use App\Models\Etablissement;

class EtablissementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(CreateEtablissementRequest $request)
    {
        dd('ok');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UpdateEtablissementRequest $request)
    {
        Etablissement::updateOrCreate([
                                    'idetablissement' => $request->idetablissement
                                ],
                                [
                                    'nom' => $request->nom,
                                    'abbr' => $request->abbr
                                ]); 

        Flashy::success('Action effectuée avec succès');
        return redirect()->back();     
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        dd('show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        dd('edit');
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        dd('update');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // dd('p');
        Etablissement::destroy($id);
        // Flashy
        return redirect()->back();
    }
}

app/Http/Controllers/Etablissements/DashboardController.php
<?php

namespace App\Http\Controllers\Etablissements;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Controllers\DeclarationController;
use App\Http\Requests\CreateUserRequestEtablissement;
use App\Http\Requests\UpdateUSerRequest;
use App\Models\Personne;
use App\Models\Etablissement;
use App\Models\Users_etablissement;
use App\Models\Declaration;
use App\DataTables\Etablissements\ListeNotificationsDataTable;
use App\DataTables\Etablissements\ArchivesDataTable;
use App\DataTables\Etablissements\ListeUtilisateursEtablissementDataTable;
use DB;
use Hash;
use Flashy;

class DashboardController extends Controller
{
	public function __construct()
	{
		$this->middleware(['auth:users_etablissement','checkUserRole','checkAuth','slugMiddleware']);
	}

	public function index1(){
		$slug = Etablissement::find(auth()->user()->idetablissement)->slug;
		return redirect()->route('etablissement.index',$slug);
	}

	public function index(Etablissement $etablissement){
		return view('etablissements.welcome',compact('etablissement'));
	}

	public function acceuil(Etablissement $etablissement,ListeNotificationsDataTable $dataTables){
		return $dataTables->with([
									'idetablissement' => auth()->user()->idetablissement,
									'etablissement_slug' => $etablissement->slug,
									'user' => auth()->user()
								])
							->render('etablissements.acceuil');

	}

	public function archives(Etablissement $etablissement,ArchivesDataTable $dataTables){
		return $dataTables->with([
									'idetablissement' => auth()->user()->idetablissement,
									'etablissement_slug' => $etablissement->slug,
									'user' => auth()->user()
								])
							->render('etablissements.acceuil');

	}

	public function viewDeclaration(Etablissement $etablissement,Declaration $declaration){
		$declaration = DeclarationController::edit($declaration->iddeclaration);
		return view('etablissements.view_doc_naiss',compact('declaration'));
	}

	public function create_declaration(Etablissement $etablissement){
		return view('etablissements.form_declaration',compact('etablissement'));
	}

	public function edit_declaration(Etablissement $etablissement, Declaration $declaration){
		$declaration = DeclarationController::edit($declaration->iddeclaration);

		return view('etablissements.form_edit_declaration',compact('declaration','etablissement'));
	}
	public function send_declaration(Etablissement $etablissement, Declaration $declaration){
		$declaration->statut = 2;
		$declaration->date_envoi = DB::raw('NOW()');
		$declaration->save();
        Flashy::success('Dossier envoyé avec succès');

		return redirect()->back();
	}
	public function destroy_declaration(Etablissement $etablissement, Declaration $declaration){
		$declaration->destroy($declaration->iddeclaration);
        Flashy::success('Dossier supprimé');

		return redirect()->back();
	}


	public function createuser(CreateUserRequestEtablissement  $request){
		$user = Personne::updateOrCreate([
									'numIdN' => $request->user_id
								],
								[
									'nom' => $request->user_nom,
									'prenom' => $request->user_prenom,
								]); 

		 $compte = Users_etablissement::updateOrCreate([
									'idpersonne' => $user->idpersonne
								],
								[
									'pseudo' => $request->pseudo,
									'password' => Hash::make('password'),
									'profil' => $request->user_profil,
									'idetablissement' => auth()->user()->idetablissement,
								]);

        Flashy::success('Utilisateur crée avec succès');

		return redirect()->back();
	}

	public function getUsers(ListeUtilisateursEtablissementDataTable $dataTables){
		return $dataTables->with([
									'idetablissement' => auth()->user()->idetablissement
								])
							->render('etablissements.liste_users');
	}
	public function updateUser(UpdateUSerRequest $request){
		$user = Users_etablissement::find($request->iduser)->update(['profil'=>$request->profil]);
        Flashy::success('Utilisateur mis en jour avec succès');
		
		return redirect()->back();
	}
}
 

resources/views/etablissements/acceuil.blade.php
@extends('etablissements.layouts.master')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')
<div class="card-body">
	<div>
		{{-- <h3>Accueil</h3> --}}
		<p>Notifications en cours</p>
		<hr>
		<br>
	</div>
	<div >
		{!!$dataTable->table() !!}
	</div>
</div>	
@stop
@push('scripts')
{!!$dataTable->scripts() !!}
@endpush

resources/views/etablissements/liste_users.blade.php
@inject('etablissement', 'App\Models\Etablissement')
@php
      $slug = $etablissement::find(auth()->user()->idetablissement)->slug;
@endphp
@extends('etablissements.layouts.master')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')
<div class="container">
	<button type="button" class="addModal btn btn-info" data-toggle="modal" data-target="#addModal">
  		 <span class="fa fa-plus"> </span> Nouveau Utilisateur
	</button><br><br>
	<div >
		{!!$dataTable->table() !!}
	</div>

	<!-- Modal -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Modifier</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {{-- msg d'erreur --}}
        {{-- Formulaire Edition--}}
        <form id="etudiantForm" action="{{ route('etablissement.update_user',$slug) }}" method="POST" name="etudiantForm" class="form-horizontal">
            @csrf
           <input type="hidden" name="iduser" id="iduser" value="">
            <div class="form-group">
                <label for="profil"  class="control-label">Profil de l'utilisateur</label>
                <div class="col-sm-12">
                   	<select class="form-control" id="profil" name="profil"   required="required">
                   		<option value="agent">Agent</option>
                   		<option value="admin">admin</option>
                   	</select>
                </div>
            </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
	        <button type="submit" class="save btn btn-primary">Enregistrer</button>
	      </div>
        </form>

      </div>
    </div>
  </div>
</div>

<!-- Modal Creation-->
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Ajouter</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {{-- msg d'erreur --}}
        {{-- Formulaire Creation --}}
        <form id="etudiantFormCreate" action="{{ route('etablissement.create_user',$slug) }}" method="POST" name="etudiantFormCreate" class="form-horizontal_create">
            @csrf
            <div class="form-group">
                  <label for="pseudo"  class="control-label">Pseudo</label>
                  <div class="col-sm-12">
                      <input type="text"  class="form-control" id="pseudo" name="pseudo"  maxlength="50" required="">
                  </div>
              </div>
            <div class="form-group">
                <label for="user_profil"  class="control-label">Profil de l'utilisateur</label>
                <div class="col-sm-12">
                    <select class="form-control" id="user_profil" name="user_profil"   required="required">
                      <option value="agent">Agent</option>
                      <option value="admin">admin</option>
                    </select>
                </div>
            </div>
            <hr>
            <div id="user-etablissement">
              <div class="form-group">
                  <label for="user_id"  class="control-label">N° Identification</label>
                  <div class="col-sm-12">
                      <input type="text"  class="form-control" id="user_id" name="user_id"  maxlength="50" required="">
                  </div>
              </div>
              
              <div class="form-group">
                  <label for="user_nom"  class="control-label">Nom</label>
                  <div class="col-sm-12">
                      <input type="text"  class="form-control" id="user_nom" name="user_nom"  maxlength="50" required="">
                  </div>
              </div>
              <div class="form-group">
                  <label for="user_prenom"  class="control-label">Prenom</label>
                  <div class="col-sm-12">
                      <input type="text"  class="form-control" id="user_prenom" name="user_prenom"  maxlength="50" required="">
                  </div>
              </div>
            </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
          <button type="submit" class="save btn btn-primary">Enregistrer</button>
        </div>
        </form>
        
      </div>
    </div>
  </div>
</div>
</div>	
@stop
@push('scripts')
{!!$dataTable->scripts() !!}

<script type="text/javascript">
  
  {{-- Ajout étudiant formulaire --}}
  $(document).on('click', '.addModal', function() {
      $('#msgErrors').html('');
      $('#msgErrors').attr('hidden','true');

    $('.modal-title').text('Ajouter');
    // resetmodalData()
    $('.form-horizontal_create').trigger("reset");
    $('.form-horizontal_create').show();
    $('#myModal').modal('show');
    });

  {{-- edition du formulaire --}}
  $(document).on('click', '.edit-modal', function() {
        $('#msgErrors').html('');
          $('#msgErrors').attr('hidden','true');

      $('#footer_action_button').text(" Update");
      $('#footer_action_button').addClass('fa fa-check');
      $('#footer_action_button').removeClass('fa fa-trash');
      $('.actionBtn').addClass('btn-success');
      $('.actionBtn').removeClass('btn-danger');
      $('.actionBtn').removeClass('delete');
      $('.actionBtn').addClass('edit');
      $('.modal-title').text('Modifier');
      $('.deleteContent').hide();
      $('.form-horizontal').show();
      var stuff = $(this).data('info').split(',');
      fillmodalData(stuff)
      $('#myModal').modal('show');
      });

  // remplissage formulaire par les donnée d'une ligne selectionée
  function fillmodalData(details){
      $('#iduser').val(details[0]);
      $('#profil').val(details[1]);
      // $('#abbr').val(details[2]);
      }

  function resetmodalData(){
      $('#iduser').val('');
      $('#profil').val('');
      }



  {{-- Suppression  --}}
  $(document).on('click', '.delete-modal', function() {
    $('#footer_action_button').text(" Delete");
    $('#footer_action_button').removeClass('glyphicon-check');
    $('#footer_action_button').addClass('glyphicon-trash');
    $('.actionBtn').removeClass('btn-success');
    $('.actionBtn').addClass('btn-danger');
    $('.actionBtn').removeClass('edit');
    $('.actionBtn').addClass('delete');
    $('.modal-title').text('Delete');
    $('.deleteContent').show();
    $('.form-horizontal').hide();
    var stuff = $(this).data('info').split(',');
    $('.divd').text(stuff[0]);
    $('.dname').html(stuff[1] +" "+stuff[2]);
    $('#myModal').modal('show');
  });

</script>
@endpush

resources/views/etablissements/view_doc_naiss.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="Bil Wifi" content="{{ config('app.name') }} by KinDev">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href={{ asset('favicon.ico') }}>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ !empty ($title) ? $title .' | '. config('app.name') : config('app.name') }}  </title>

    @yield('stylesheet1')
        <!-- Custom CSS -->
    <link href="{{ asset('bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
     <link href="{{ asset('bootstrap/icons/font-awesome/css/fontawesome-all.css') }}" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    @yield('stylesheet')
    <!-- Coustom styleSheet--->
    @stack('stylesheets')


</head>

  <body>

{{-- @include('etablissements.layouts.partials._header')
@include('etablissements.layouts.partials._header_img')
@include('etablissements.layouts.partials._nav') --}}
<br>
    <div class="container font-weight-bold text-monospace">
        

        <div class="card bg-light " >
  <div class="card-header">
  	Hôpital : {{ $declaration['etablissement']['nom'] }} <br>
  	Adresse : {{ $declaration['etablissement']['idadresse'] }}
  </div>
  <div class="card-body">
    

    <table class="table ">
 {{--  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead> --}}
  <tbody>
  	<tr><td colspan="2"><h3>Identité de la mère</h3></td></tr>
    <tr>
      <td>Nom</td>
      <td>{{ $declaration['mere']['nom'] }}</td>
    </tr>
    <tr>
      <td>Postnom</td>
      <td>{{ $declaration['mere']['postnom'] }}</td>
    </tr>
    <tr>
      <td>Prenom</td>
      <td>{{ $declaration['mere']['prenom'] }}</td>
    </tr>
    <tr>
      <td>Lieu de naissance</td>
      <td>{{ $declaration['mere']['lieuNaissance'] }}</td>
    </tr>
    <tr>
      <td>Date de naissance</td>
      <td>{{ $declaration['mere']['dateNaissance'] }}</td>
    </tr>
    <tr>
      <td>Nationalité</td>
      <td>{{ $declaration['mere']['nationalite'] }}nation</td>
    </tr>
    <tr>
      <td>Profession</td>
      <td>{{ $declaration['mere']['profession'] }}Adresse</td>
    </tr>
    <tr>
      <td>Télephone</td>
      <td>{{ $declaration['mere']['telephone'] }}tel</td>
    </tr>


    <tr><td colspan="2"><h3>Identité du pére</h3></td></tr>
    <tr>
      <td>Nom</td>
      <td>{{ $declaration['pere']['nom'] }}nom</td>
    </tr>
    <tr>
      <td>Postnom</td>
      <td>{{ $declaration['pere']['postnom'] }}</td>
    </tr>
    <tr>
      <td>Prenom</td>
      <td>{{ $declaration['pere']['prenom'] }}</td>
    </tr>
    <tr>
      <td>Lieu de naissance</td>
      <td>{{ $declaration['pere']['lieuNaissance'] }}</td>
    </tr>
    <tr>
      <td>Date de naissance</td>
      <td>{{ $declaration['pere']['dateNaissance'] }}</td>
    </tr>
    <tr>
      <td>Nationalité</td>
      <td>{{ $declaration['pere']['nationalite'] }}</td>
    </tr>
    <tr>
      <td>Profession</td>
      <td>{{ $declaration['pere']['profession'] }}</td>
    </tr>
    <tr>
      <td>Télephone</td>
      <td>{{ $declaration['pere']['telephone'] }}</td>
    </tr>

    <tr><td colspan="2"><h3>Identité du nouveau né</h3></td></tr>
    <tr>
      <td>Nom</td>
      <td>{{ $declaration['enfant']['nom'] }}</td>
    </tr>
    <tr>
      <td>Postnom</td>
      <td>{{ $declaration['enfant']['postnom'] }}</td>
    </tr>
    <tr>
      <td>Prenom</td>
      <td>{{ $declaration['enfant']['prenom'] }}</td>
    </tr>
    <tr>
      <td>Lieu de naissance</td>
      <td>{{ $declaration['enfant']['lieuNaissance'] }}</td>
    </tr>
    <tr>
      <td>Date de naissance</td>
      <td>{{ $declaration['enfant']['dateNaissance'] }}</td>
    </tr>
    <tr>
      <td>{{ $declaration['enfant']['nom'] }}Nationalité</td>
      <td>{{ $declaration['enfant']['nationalite'] }}</td>
    </tr>
    

    <tr><td colspan="2"><h3>Informations sociales</h3></td></tr>
    <tr>
      <td>Situation matrimoniale</td>
      <td>{{ $declaration['declaration']['cituation_matrimonial_parent'] }}</td>
    </tr>
    <tr>
      <td>Cituation amoureuse</td>
      <td>{{ $declaration['declaration']['cituation_amoureuse_parent'] }}</td>
    </tr>
    <tr>
      <td>Commentaire</td>
      <td>{{ $declaration['declaration']['commentaire'] }}</td>
    </tr>
  
  	    <tr><td colspan="2"><h3>Déclarant</h3></td></tr>
    <tr>
      <td>Nom</td>
      <td>{{ $declaration['declarant']['nom'] }}</td>
    </tr>
    <tr>
      <td>Postnom</td>
      <td>{{ $declaration['declarant']['postnom'] }}</td>
    </tr>
    <tr>
      <td>Prenom</td>
      <td>{{ $declaration['declarant']['prenom'] }}</td>
    </tr>
    <tr>
      <td>Lieu de naissance</td>
      <td>{{ $declaration['declarant']['lieuNaissance'] }}</td>
    </tr>
   
    <tr>
      <td>Nationalité</td>
      <td>{{ $declaration['declarant']['nationalite'] }}</td>
    </tr>

    <tr>
      <td>Télephone</td>
      <td>{{ $declaration['declarant']['telephone'] }}</td>
    </tr>
    
  </tbody>
</table>








  </div>
  <div class="card-footer">
  	<p class="text-right">Kinshasa : {{ $declaration['declaration']['created_at'] }}</p>
  	
  </div>
</div>
<div class="container">
            <a href="{{ url()->previous() }}">RETOUR</a>
        </div>

    </div>



    <script src={{ asset('backend/assets/libs/jquery/dist/jquery.min.js') }}></script>
    <script src={{ asset('backend/assets/libs/bootstrap/dist/js/bootstrap.min.js') }}></script>
    
  
    <!-- this page js -->

@stack('scripts')
@include('flashy::message')

  </body>

<!-- Mirrored from getbootstrap.com/docs/4.1/examples/pricing/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 07 Nov 2018 23:41:46 GMT -->
</html>