routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/form', function () {
    return view('matrix.html.ltr.web');
    // return view('partials.includes.formulaires.form');
});
// Route::get('/', function () {
//     return view('matrix.html.ltr.web');
//     // return view('partials.includes.formulaires.form');
// });

Route::get('/test1/{etablissement}','Etablissements\DashboardController@test');

Route::get('/testAuth', function () {
    return App\Models\Agents_commune::getUsersByCommune(1);
})->name('test');

// Welcome
Route::get('/',function(){
	return view('welcomeApp');
})->name('login');
Route::post('/',function(){
	$etablissemnt = App\Models\Etablissement::where('slug',request()->slug)->first(	);
	if($etablissemnt){
		return redirect('/'.$etablissemnt->slug);
	}
	Flashy::error('Le Slug entré n\'est pas disponible');
	return redirect()->back();
});

Route::get('logout',function(){
  auth()->logout();
  return redirect('/');
})->name('logout');

/**
* Route pour les agents de la commune
*
**/
// Route::domain('commune.snen.local')->group(function(){
// 		Route::get('/', function () {
// 		    return redirect()->route('commune');
// 		});
Route::get('/agent-commune', 'Auth\AgentCommuneController@showLoginForm')->name('commune');
Route::post('/agent-commune', 'Auth\AgentCommuneController@login')->name('login_agent_commune');
Route::name('commune.')->group(function () {
		Route::get('/welcome','Communes\DashboardController@index')->name('index');
		Route::get('/accueil','Communes\DashboardController@acceuil')->name('accueil');
		Route::get('/archives','Communes\DashboardController@archives')->name('archive');
		Route::get('/view/{declaration}','Communes\DashboardController@viewDeclaration')->name('view_declaration');
		Route::get('/etablissements','Communes\DashboardController@getEtablissements')->name('get_etablissements');
		Route::post('/createEtablissment','Communes\DashboardController@createEtablissements')->name('create_etablissement');
		Route::get('/users','Communes\DashboardController@getUsers')->name('get_users');
		Route::post('/createUser','Communes\DashboardController@createUser')->name('create_user');
		Route::post('/updateUser','Communes\DashboardController@updateUSer')->name('update_user');

		Route::get('/create','Communes\DashboardController@create_declaration')->name('create_declaration');
		Route::post('/create','DeclarationController@store')->name('create_declaration');

		Route::get('/edit/{declaration}','Communes\DashboardController@edit_declaration')->name('edit_declaration');
		Route::post('/edit/{declaration}','DeclarationController@store')->name('edit_declaration');
		Route::get('/archive/{declaration}','Communes\DashboardController@archive_declaration')->name('archive_declaration');


		Route::resource('/crud_etablissements','EtablissementController');

		Route::get('logout-commune',function(){
			auth()->logout();
			request()->session()->flush();

  			return redirect()->route('commune');
		})->name('logout');

	});
// });

// Route pourles utilisateur des établissement 
// Route::domain('hopital.snen.local')->group(function(){
// 		Route::get('/', function () {
// 		    return redirect()->route('user_etablissement');
// 		});

	Route::get('/{etablissement}/login', 'Auth\UserEtablissementController@showLoginForm')->name('user_etablissement');
	Route::post('/{etablissement}/login', 'Auth\UserEtablissementController@login')->name('login_user_etablissement');

	Route::name('etablissement.')->group(function () {
			Route::get('/slug','Etablissements\DashboardController@index1')->name('index1');

			Route::get('/{etablissement}/welcome','Etablissements\DashboardController@index')->name('index');
			Route::get('/{etablissement}/accueil','Etablissements\DashboardController@acceuil')->name('accueil');
			Route::get('/{etablissement}/archives','Etablissements\DashboardController@archives')->name('archive_declaration');
			Route::get('/{etablissement}/create','Etablissements\DashboardController@create_declaration')->name('create_declaration');
			Route::post('/{etablissement}/create','DeclarationController@store')->name('create_declaration');
			Route::get('/{etablissement}/edit/{declaration}','Etablissements\DashboardController@edit_declaration')->name('edit_declaration');
			Route::post('/{etablissement}/edit/{declaration}','DeclarationController@store')->name('edit_declaration');
			Route::get('/{etablissement}/send/{declaration}','Etablissements\DashboardController@send_declaration')->name('send_declaration');
			Route::get('/{etablissement}/destoy/{declaration}','Etablissements\DashboardController@destroy_declaration')->name('delete_declaration');

			Route::get('/{etablissement}/users','Etablissements\DashboardController@getUsers')->name('get_users');
			Route::post('/{etablissement}/createUser','Etablissements\DashboardController@createUser')->name('create_user');
			Route::post('/{etablissement}/updateUser','Etablissements\DashboardController@updateUSer')->name('update_user');
			

			Route::get('/{etablissement}/view/{declaration}','Etablissements\DashboardController@viewDeclaration')->name('view_declaration');

			Route::get('logout-etablissement/{etablissement}',function(App\Models\Etablissement $etablissement){
				\Auth::logout();
				request()->session()->flush();
	  			return redirect()->route('user_etablissement',$etablissement->slug);
			})->name('logout');


		});
	Route::get('/{etablissement}', function(App\Models\Etablissement $etablissement){
		return redirect()->route('user_etablissement',$etablissement->slug);
	});

// });

resources/views/etablissements/layouts/partials/_footer.blade.php
      <a href="http://www.kindev243.com" target="_blank" style="text-decoration: none;"><p class="mt-5 mb-3 text-muted text-center">&copy; 2018 - {{ date('Y') }} | ISPT-KIN</p></a>

resources/views/etablissements/layouts/partials/_header.blade.php
@php
if (!empty(auth()->user()->idagents_commune)) {
	$slug = $etablissement->slug;
}else{
$slug = App\Models\Etablissement::find(auth()->user()->idetablissement)->slug ;

}

@endphp
@auth('users_etablissement')
<div class="d-flex flex-column flex-md-row align-items-center p-0 px-md- mb-0 bg-white shadow-sm" style="border: none">
      <h5 class="my-0 mr-md-auto font-weight-normal">Notification électronique des naissances</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="#">aide</a>
        <a class="p-2 text-dark" href="#">mon profil</a>
        <a class="p-2 text-dark" href="{{ route('etablissement.logout',$slug) }}">déconnexion</a>
      </nav>
</div>
@endauth
@auth('agents_commune')
<div class="d-flex flex-column flex-md-row align-items-center p-0 px-md- mb-0 shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">Maison Communale de Lingwala</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="#">aide</a>
        <a class="p-2 text-dark" href="#">mon profil</a>
        <a class="p-2 text-dark" href="{{ route('commune.logout') }}">déconnexion</a>
      </nav>
</div>
@endauth

resources/views/etablissements/layouts/partials/_header_img.blade.php
<div class="card bg-dark text-white" style="margin-bottom: 0px">
  <img class="img-fluid" style="height: 300px" src="{{ asset('img/snenimg.jpg') }}">
</div>

resources/views/etablissements/layouts/partials/_nav.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      @auth('users_etablissement')
        {{-- MENU POUR LES ETABLISSEMENT --}}
        @inject('etablissement', 'App\Models\Etablissement')
        @php
        $slug = $etablissement::find(auth()->user()->idetablissement)->slug;
        @endphp
        
        <li class="nav-item active">
          <a class="nav-link" href="{{ route('etablissement.index',$slug) }}">Accueil 

            {{-- <span class="sr-only"></span> --}}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ route('etablissement.create_declaration',$slug) }}">Créer</a>
        </li>
      {{--   <li class="nav-item">
          <a class="nav-link" href="#">Recherche</a>
        </li> --}}
         {{-- Si Admin commune --}}

        @if(auth()->user()->profil == 'admin')
        <li class="nav-item">
          <a class="nav-link" href="{{ route('etablissement.get_users',$slug) }}">Utilisateurs</a>
        </li>
        @endif
      @endauth

      {{-- MENU POUR LA COMMUNE --}}
      @auth('agents_commune')
        <li class="nav-item active">
          <a class="nav-link" href="{{ route('commune.accueil') }}">Accueil 

            {{-- <span class="sr-only"></span> --}}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ ''}}">Créer</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Recherche</a>
        </li>
        {{-- Si Admin commune --}}

        @if(auth()->user()->profil == 'admin')
        <li class="nav-item">
          <a class="nav-link" href="{{ route('commune.get_etablissements') }}">Etablissements</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ route('commune.get_users') }}">Utilisateurs</a>
        </li>
        @endif
      @endauth
      </ul>
      
  </div>
</nav>