routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/form', function () {
    return view('matrix.html.ltr.web');
    // return view('partials.includes.formulaires.form');
});
// Route::get('/', function () {
//     return view('matrix.html.ltr.web');
//     // return view('partials.includes.formulaires.form');
// });

Route::get('/test1/{etablissement}','Etablissements\DashboardController@test');

Route::get('/testAuth', function () {
    return App\Models\Agents_commune::getUsersByCommune(1);
})->name('test');

// Welcome
Route::get('/',function(){
	return view('welcomeApp');
})->name('login');
Route::post('/',function(){
	$etablissemnt = App\Models\Etablissement::where('slug',request()->slug)->first(	);
	if($etablissemnt){
		return redirect('/'.$etablissemnt->slug);
	}
	Flashy::error('Le Slug entré n\'est pas disponible');
	return redirect()->back();
});

Route::get('logout',function(){
  auth()->logout();
  return redirect('/');
})->name('logout');

/**
* Route pour les agents de la commune
*
**/
// Route::domain('commune.snen.local')->group(function(){
// 		Route::get('/', function () {
// 		    return redirect()->route('commune');
// 		});
Route::get('/agent-commune', 'Auth\AgentCommuneController@showLoginForm')->name('commune');
Route::post('/agent-commune', 'Auth\AgentCommuneController@login')->name('login_agent_commune');
Route::name('commune.')->group(function () {
		Route::get('/welcome','Communes\DashboardController@index')->name('index');
		Route::get('/accueil','Communes\DashboardController@acceuil')->name('accueil');
		Route::get('/archives','Communes\DashboardController@archives')->name('archive');
		Route::get('/view/{declaration}','Communes\DashboardController@viewDeclaration')->name('view_declaration');
		Route::get('/etablissements','Communes\DashboardController@getEtablissements')->name('get_etablissements');
		Route::post('/createEtablissment','Communes\DashboardController@createEtablissements')->name('create_etablissement');
		Route::get('/users','Communes\DashboardController@getUsers')->name('get_users');
		Route::post('/createUser','Communes\DashboardController@createUser')->name('create_user');
		Route::post('/updateUser','Communes\DashboardController@updateUSer')->name('update_user');

		Route::get('/create','Communes\DashboardController@create_declaration')->name('create_declaration');
		Route::post('/create','DeclarationController@store')->name('create_declaration');

		Route::get('/edit/{declaration}','Communes\DashboardController@edit_declaration')->name('edit_declaration');
		Route::post('/edit/{declaration}','DeclarationController@store')->name('edit_declaration');
		Route::get('/archive/{declaration}','Communes\DashboardController@archive_declaration')->name('archive_declaration');


		Route::resource('/crud_etablissements','EtablissementController');

		Route::get('logout-commune',function(){
			auth()->logout();
			request()->session()->flush();

  			return redirect()->route('commune');
		})->name('logout');

	});
// });

// Route pourles utilisateur des établissement 
// Route::domain('hopital.snen.local')->group(function(){
// 		Route::get('/', function () {
// 		    return redirect()->route('user_etablissement');
// 		});

	Route::get('/{etablissement}/login', 'Auth\UserEtablissementController@showLoginForm')->name('user_etablissement');
	Route::post('/{etablissement}/login', 'Auth\UserEtablissementController@login')->name('login_user_etablissement');

	Route::name('etablissement.')->group(function () {
			Route::get('/slug','Etablissements\DashboardController@index1')->name('index1');

			Route::get('/{etablissement}/welcome','Etablissements\DashboardController@index')->name('index');
			Route::get('/{etablissement}/accueil','Etablissements\DashboardController@acceuil')->name('accueil');
			Route::get('/{etablissement}/archives','Etablissements\DashboardController@archives')->name('archive_declaration');
			Route::get('/{etablissement}/create','Etablissements\DashboardController@create_declaration')->name('create_declaration');
			Route::post('/{etablissement}/create','DeclarationController@store')->name('create_declaration');
			Route::get('/{etablissement}/edit/{declaration}','Etablissements\DashboardController@edit_declaration')->name('edit_declaration');
			Route::post('/{etablissement}/edit/{declaration}','DeclarationController@store')->name('edit_declaration');
			Route::get('/{etablissement}/send/{declaration}','Etablissements\DashboardController@send_declaration')->name('send_declaration');
			Route::get('/{etablissement}/destoy/{declaration}','Etablissements\DashboardController@destroy_declaration')->name('delete_declaration');

			Route::get('/{etablissement}/users','Etablissements\DashboardController@getUsers')->name('get_users');
			Route::post('/{etablissement}/createUser','Etablissements\DashboardController@createUser')->name('create_user');
			Route::post('/{etablissement}/updateUser','Etablissements\DashboardController@updateUSer')->name('update_user');
			

			Route::get('/{etablissement}/view/{declaration}','Etablissements\DashboardController@viewDeclaration')->name('view_declaration');

			Route::get('logout-etablissement/{etablissement}',function(App\Models\Etablissement $etablissement){
				\Auth::logout();
				request()->session()->flush();
	  			return redirect()->route('user_etablissement',$etablissement->slug);
			})->name('logout');


		});
	Route::get('/{etablissement}', function(App\Models\Etablissement $etablissement){
		return redirect()->route('user_etablissement',$etablissement->slug);
	});

// });

app/Http/Controllers/Communes/DashboardController.php
<?php

namespace App\Http\Controllers\Communes;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\DataTables\Communes\ListeNotificationsDataTable;
use App\DataTables\Communes\ArchivesDataTable;
use App\DataTables\Communes\ListeEtablissementsDataTable;
use App\DataTables\Communes\ListeUtilisateursDataTable;
use App\Http\Requests\CreateEtablissementRequest;
use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\UpdateUSerRequest;
use App\Models\Etablissement;
use App\Models\Personne;
use App\Models\Declaration;
use App\Http\Controllers\DeclarationController;

use App\Models\Users_etablissement;
use App\Models\Agents_commune;
use Hash;
use Flashy;





class DashboardController extends Controller
{
   
    public function __construct()
    {
        $this->middleware(['auth:agents_commune','checkAuth']);
    }

    public function index(){
        return view('communes.welcome');
    }

    public function acceuil(ListeNotificationsDataTable $dataTables){
    	return $dataTables->with([
                                    'user' => auth()->user()
                                ])
                            ->render('communes.acceuil');
    }

    public function archives(ArchivesDataTable $dataTables){
        return $dataTables->with([
                                    'user' => auth()->user()
                                ])
                            ->render('communes.acceuil');
    }
    public function viewDeclaration(Declaration $declaration){
        $declaration = DeclarationController::edit($declaration->iddeclaration);
        return view('etablissements.view_doc_naiss',compact('declaration'));
    }

    public function getEtablissements(ListeEtablissementsDataTable  $dataTables){
        return $dataTables->render('communes.liste_etablissements');
    }
    public function createEtablissements(CreateEtablissementRequest  $request){
        $admin = Personne::updateOrCreate([
                                    'numIdN' => $request->user_id
                                ],
                                [
                                    'nom' => $request->user_nom,
                                    'prenom' => $request->user_prenom
                                ]);
                                // dd(request()->request); 
        $etablissement = Etablissement::updateOrCreate([
                                    'idetablissement' => $request->idetablissement
                                ],
                                [
                                    'nom' => $request->nom,
                                    'abbr' => $request->abbr,
                                    'idadresse' => $request->adresse
                                ]);
        $compte = Users_etablissement::updateOrCreate([
                                    'idpersonne' => $admin->idpersonne
                                ],
                                [
                                    'pseudo' => 'admin-'.$etablissement->slug,
                                    'password' => Hash::make('azerty'),
                                    'profil' => 'admin',
                                    'isAdmin'=> true,
                                    'idetablissement' => $etablissement->idetablissement,
                                ]);
        // 
        // FLASHYYYYYYYYYYYYYYYYY
        // ------------------------------------------
        Flashy::success('Opération effectué avec succès');  
        return redirect()->route('commune.get_etablissements');
    }

    public function createuser(CreateUserRequest  $request){
        $user = Personne::updateOrCreate([
                                    'numIdN' => $request->user_id
                                ],
                                [
                                    'nom' => $request->user_nom,
                                    'prenom' => $request->user_prenom,
                                ]); 
         $compte = Agents_commune::updateOrCreate([
                                    'idpersonne' => $user->idpersonne
                                ],
                                [
                                    'pseudo' => $request->user_pseudo,
                                    'password' => Hash::make('azerty'),
                                    'profil' => $request->user_profil,
                                    // 'idcommune' => auth()->user()->idcommune,
                                ]);
        Flashy::success('Opération effectué avec succès');
        return redirect()->route('commune.get_users');
    }

    public function getUsers(ListeUtilisateursDataTable $dataTables){
        return $dataTables->with([
                                    'idcommune' => auth()->user()->idcommune
                                ])
                            ->render('communes.liste_users');
    }
    public function updateUser(UpdateUSerRequest $request){
        $user = Agents_commune::find($request->iduser)->update(['profil'=>$request->profil]);
        // Flashyyy
        // ---------------
        Flashy::success('Utilisateur modifié avec succès');
        return redirect()->back();
    }
    
    public function create_declaration(Etablissement $etablissement){
        return view('etablissements.form_declaration',compact('etablissement'));
    }
    public function edit_declaration(Declaration $declaration){
        $etablissement = Etablissement::find($declaration->idetablissement);
        $declaration = DeclarationController::edit($declaration->iddeclaration);
        return view('etablissements.form_edit_declaration',compact('declaration','etablissement','idetablissement'));
    }

    public function archive_declaration(Declaration $declaration){
        $declaration->statut = 3;
        $declaration->save();

        Flashy::success('Dossier archivé avec succès');
        return redirect()->back();
    }
}

resources/views/communes/acceuil.blade.php
@extends('communes.layouts.master')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')
<div class='content'>
	{{-- <h3>Accueil</h3> --}}
	<h5>Notifications réçus</h5>
	<hr>
	<br>
</div>
<div class="card">
  <div class="card-body">
	{!!$dataTable->table() !!}
  </div>
</div>
@stop
@push('scripts')
{!!$dataTable->scripts() !!}
@endpush

resources/views/communes/liste_etablissements.blade.php
@extends('communes.layouts.master')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')
<div class="container">
	<button type="button" class="addModal btn btn-info" data-toggle="modal" data-target="#addModal">
  		 <span class="fa fa-plus"> </span> Nouveau établissement
	</button><br><br>
	<div >
	  <div >
	  	<div class="create">
		</div>
		{!!$dataTable->table() !!}
    

<!-- Modal -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Modifier</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {{-- msg d'erreur --}}
        {{-- Formulaire Edition--}}
        <form id="etudiantForm" action="{{ route('commune.crud_etablissements.store') }}" method="POST" name="etudiantForm" class="form-horizontal">
            @csrf
           <input type="hidden" name="idetablissement" id="idetablissement">
            <div class="form-group">
                <label for="nom"  class="control-label">Nom de l'établissement</label>
                <div class="col-sm-12">
                    <input type="text"  class="form-control" id="nom" name="nom"   maxlength="50" required="required">
                </div>
            </div>
            <div class="form-group">
                <label for="nom"  class="control-label">Abbreviation de l'établissement</label>
                <div class="col-sm-12">
                    <input type="text"  class="form-control" id="abbr" name="abbr"  maxlength="50" required="">
                </div>
            </div>
            <div class="form-group">
                <label for="adresse"  class="control-label">Adresse</label>
                <div class="col-sm-12">
                    <input type="text"  class="form-control" id="adresse" name="adresse"  maxlength="50" required="">
                </div>
            </div>
           
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
	        <button type="submit" class="save btn btn-primary">Enregistrer</button>
	      </div>
        </form>

      </div>
    </div>
  </div>
</div>

<!-- Modal Creation-->
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Ajouter</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {{-- msg d'erreur --}}
        {{-- Formulaire Creation --}}
        <form id="etudiantFormCreate" action="{{ route('commune.create_etablissement') }}" method="POST" name="etudiantFormCreate" class="form-horizontal_create">
            @csrf
           <input type="hidden" name="idetablissement" id="idetablissement">
            <div class="form-group">
                <label for="nom"  class="control-label">Nom de l'établissement</label>
                <div class="col-sm-12">
                    <input type="text"  class="form-control" id="nom" name="nom"   maxlength="50" required="required">
                </div>
            </div>
            <div class="form-group">
                <label for="nom"  class="control-label">Abbreviation de l'établissement</label>
                <div class="col-sm-12">
                    <input type="text"  class="form-control" id="abbr" name="abbr"  maxlength="50" required="">
                </div>
            </div>
            <div class="form-group">
                <label for="adresse"  class="control-label">Adresse</label>
                <div class="col-sm-12">
                    <input type="text"  class="form-control" id="adresse" name="adresse"  maxlength="50" required="">
                </div>
            </div>
            <div id="user-etablissement">
            	<hr>
            	<div class="card-title">Information de l'utilisateur admin</div>
            	<div class="form-group">
	                <label for="user_id"  class="control-label">N° Identification</label>
	                <div class="col-sm-12">
	                    <input type="text"  class="form-control" id="user_id" name="user_id"  maxlength="50" required="">
	                </div>
           		</div>
           		<div class="form-group">
	                <label for="user_nom"  class="control-label">Nom</label>
	                <div class="col-sm-12">
	                    <input type="text"  class="form-control" id="user_nom" name="user_nom"  maxlength="50" required="">
	                </div>
           		</div>
           		<div class="form-group">
	                <label for="user_prenom"  class="control-label">Prenom</label>
	                <div class="col-sm-12">
	                    <input type="text"  class="form-control" id="user_prenom" name="user_prenom"  maxlength="50" >
	                </div>
           		</div>
            </div>

	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
	        <button type="submit" class="save btn btn-primary">Enregistrer</button>
	      </div>
        </form>
        
      </div>
    </div>
  </div>
</div>








































	  </div>
	</div>
</div>	
@stop
@push('scripts')
{!!$dataTable->scripts() !!}

<script type="text/javascript">
	
	{{-- Ajout étudiant formulaire --}}
	$(document).on('click', '.addModal', function() {
	    $('#msgErrors').html('');
  		$('#msgErrors').attr('hidden','true');

		$('.modal-title').text('Ajouter');
		// resetmodalData()
		$('.form-horizontal_create').trigger("reset");
		$('.form-horizontal_create').show();
		$('#myModal').modal('show');
		});

	{{-- edition du formulaire --}}
	$(document).on('click', '.edit-modal', function() {
		    $('#msgErrors').html('');
      		$('#msgErrors').attr('hidden','true');

			$('#footer_action_button').text(" Update");
			$('#footer_action_button').addClass('fa fa-check');
			$('#footer_action_button').removeClass('fa fa-trash');
			$('.actionBtn').addClass('btn-success');
			$('.actionBtn').removeClass('btn-danger');
			$('.actionBtn').removeClass('delete');
			$('.actionBtn').addClass('edit');
			$('.modal-title').text('Modifier');
			$('.deleteContent').hide();
			$('.form-horizontal').show();
			var stuff = $(this).data('info').split(',');
			fillmodalData(stuff)
			$('#myModal').modal('show');
			});

	// remplissage formulaire par les donnée d'une ligne selectionée
	function fillmodalData(details){
			$('#idetablissement').val(details[0]);
			$('#nom').val(details[1]);
      $('#abbr').val(details[2]);
			$('#adresse').val(details[3]);
			}

	function resetmodalData(){
			$('#nom').val('');
      $('#abbr').val('');
			$('#adresse').val('');
			}



	{{-- Suppression  --}}
	$(document).on('click', '.delete-modal', function() {
		$('#footer_action_button').text(" Delete");
		$('#footer_action_button').removeClass('glyphicon-check');
		$('#footer_action_button').addClass('glyphicon-trash');
		$('.actionBtn').removeClass('btn-success');
		$('.actionBtn').addClass('btn-danger');
		$('.actionBtn').removeClass('edit');
		$('.actionBtn').addClass('delete');
		$('.modal-title').text('Delete');
		$('.deleteContent').show();
		$('.form-horizontal').hide();
		var stuff = $(this).data('info').split(',');
		$('.divd').text(stuff[0]);
		$('.dname').html(stuff[1] +" "+stuff[2]);
		$('#myModal').modal('show');
	});

</script>
@endpush

resources/views/communes/liste_users.blade.php
@extends('communes.layouts.master')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')
<div class="container">
	<button type="button" class="addModal btn btn-info" data-toggle="modal" data-target="#addModal">
  		 <span class="fa fa-plus"> </span> Nouveau Utilisateur
	</button><br><br>
	<div >
	  <div >
		{!!$dataTable->table() !!}
	  </div>
	</div>

	<!-- Modal -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Modifier</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {{-- msg d'erreur --}}
        {{-- Formulaire Edition--}}
        <form id="etudiantForm" action="{{ route('commune.update_user') }}" method="POST" name="etudiantForm" class="form-horizontal">
            @csrf
           <input type="hidden" name="iduser" id="iduser" value="">
            <div class="form-group">
                <label for="profil"  class="control-label">Profil de l'utilisateur</label>
                <div class="col-sm-12">
                   	<select class="form-control" id="profil" name="profil"   required="required">
                   		<option value="agent">Agent</option>
                   		<option value="admin">admin</option>
                   	</select>
                </div>
            </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
	        <button type="submit" class="save btn btn-primary">Enregistrer</button>
	      </div>
        </form>

      </div>
    </div>
  </div>
</div>

<!-- Modal Creation-->
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Ajouter</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {{-- msg d'erreur --}}
        {{-- Formulaire Creation --}}
        <form id="etudiantFormCreate" action="{{ route('commune.create_user') }}" method="POST" name="etudiantFormCreate" class="form-horizontal_create">
            @csrf
            <div class="form-group">
                  <label for="user_pseudo"  class="control-label">Pseudo</label>
                  <div class="col-sm-12">
                      <input type="text"  class="form-control" id="user_pseudo" name="user_pseudo"  maxlength="50" required="">
                  </div>
              </div>
            <div class="form-group">
                <label for="user_profil"  class="control-label">Profil de l'utilisateur</label>
                <div class="col-sm-12">
                    <select class="form-control" id="user_profil" name="user_profil"   required="required">
                      <option value="agent">Agent</option>
                      <option value="admin">admin</option>
                    </select>
                </div>
            </div>
            <hr>
            <div id="user-etablissement">
              <div class="form-group">
                  <label for="user_id"  class="control-label">N° Identification</label>
                  <div class="col-sm-12">
                      <input type="text"  class="form-control" id="user_id" name="user_id"  maxlength="50" required="">
                  </div>
              </div>
              
              <div class="form-group">
                  <label for="user_nom"  class="control-label">Nom</label>
                  <div class="col-sm-12">
                      <input type="text"  class="form-control" id="user_nom" name="user_nom"  maxlength="50" required="">
                  </div>
              </div>
              <div class="form-group">
                  <label for="user_prenom"  class="control-label">Prenom</label>
                  <div class="col-sm-12" required>
                      <input type="text"  class="form-control" id="user_prenom" name="user_prenom"  maxlength="50" >
                  </div>
              </div>
            </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
          <button type="submit" class="save btn btn-primary">Enregistrer</button>
        </div>
        </form>
        
      </div>
    </div>
  </div>
</div>
</div>	
@stop
@push('scripts')
{!!$dataTable->scripts() !!}

<script type="text/javascript">
  
  {{-- Ajout étudiant formulaire --}}
  $(document).on('click', '.addModal', function() {
      $('#msgErrors').html('');
      $('#msgErrors').attr('hidden','true');

    $('.modal-title').text('Ajouter');
    // resetmodalData()
    $('.form-horizontal_create').trigger("reset");
    $('.form-horizontal_create').show();
    $('#myModal').modal('show');
    });

  {{-- edition du formulaire --}}
  $(document).on('click', '.edit-modal', function() {
        $('#msgErrors').html('');
          $('#msgErrors').attr('hidden','true');

      $('#footer_action_button').text(" Update");
      $('#footer_action_button').addClass('fa fa-check');
      $('#footer_action_button').removeClass('fa fa-trash');
      $('.actionBtn').addClass('btn-success');
      $('.actionBtn').removeClass('btn-danger');
      $('.actionBtn').removeClass('delete');
      $('.actionBtn').addClass('edit');
      $('.modal-title').text('Modifier');
      $('.deleteContent').hide();
      $('.form-horizontal').show();
      var stuff = $(this).data('info').split(',');
      fillmodalData(stuff)
      $('#myModal').modal('show');
      });

  // remplissage formulaire par les donnée d'une ligne selectionée
  function fillmodalData(details){
      $('#iduser').val(details[0]);
      $('#profil').val(details[1]);
      // $('#abbr').val(details[2]);
      }

  function resetmodalData(){
      $('#iduser').val('');
      $('#profil').val('');
      }



  {{-- Suppression  --}}
  $(document).on('click', '.delete-modal', function() {
    $('#footer_action_button').text(" Delete");
    $('#footer_action_button').removeClass('glyphicon-check');
    $('#footer_action_button').addClass('glyphicon-trash');
    $('.actionBtn').removeClass('btn-success');
    $('.actionBtn').addClass('btn-danger');
    $('.actionBtn').removeClass('edit');
    $('.actionBtn').addClass('delete');
    $('.modal-title').text('Delete');
    $('.deleteContent').show();
    $('.form-horizontal').hide();
    var stuff = $(this).data('info').split(',');
    $('.divd').text(stuff[0]);
    $('.dname').html(stuff[1] +" "+stuff[2]);
    $('#myModal').modal('show');
  });

</script>
@endpush